### ISSUE TITLE
hooks broken?

### ISSUE THREAD

**Issue by ggn06awu** [jhabdas/12roads#1]
This example seems broken at present.

> TripPage.js:87 Uncaught TypeError: Cannot read property 'title' of null

Error caused by navigating through:
NPM install -> load home page -> Explore -> Click on any photo

A second photo click seems to work but a warning comes up:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
> (client)  11 --><div style="-webkit-tap-highlight
> (server)  11 --><div style="-moz-box-sizing:borde

**Comment by jhabdas** [comment]
Please reopen on the new upstream if still an issue: https://git.habd.as/jhabdas/12roads
